// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication_aspnet.Data;

#nullable disable

namespace WebApplication_aspnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251218214602_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication_aspnet.Models.City", b =>
                {
                    b.Property<int>("Nid_city")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Nid_city"));

                    b.Property<DateTime>("Dcreated_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nid_city");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("WebApplication_aspnet.Models.User", b =>
                {
                    b.Property<int>("Nid_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Nid_user"));

                    b.Property<DateTime>("Dcreated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nphone")
                        .HasColumnType("int");

                    b.Property<string>("Saddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Semail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slast_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Nid_user");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
